title: geoffl
email: g@geoffl.me
description: > # this means to ignore newlines until "baseurl:"
  Links to places on the web and occasional writing.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: gleibinger
github_username:  samekh93

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - github-pages
exclude:
  - Gemfile
  - Gemfile.lock
